on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions: 
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2